force-app/main/default/objects/AssignResourse__c/AssignResourse__c.object-meta.xml
<CustomObject>
    <label>Assign Resourse</label>
    <nameField>
        <label>Assign Resourse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assign Resourses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AssignResourse__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assign Resourses</relationshipLabel>
    <relationshipName>Assign_Resourses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AssignResourse__c/fields/DailyRate__c.field-meta.xml
<CustomField>
    <fullName>DailyRate__c</fullName>
    <label>Daily Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AssignResourse__c/fields/InvoiceTemplate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplate__c</fullName>
    <label>Invoice Template</label>
    <referenceTo>InvoiceTemplate__c</referenceTo>
    <relationshipLabel>Assign Resourses</relationshipLabel>
    <relationshipName>Assign_Resourses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AssignResourse__c/fields/ProjectRole__c.field-meta.xml
<CustomField>
    <fullName>ProjectRole__c</fullName>
    <label>Project Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce Architect</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/InvoiceTemplate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Template</label>
    <referenceTo>InvoiceTemplate__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceTemplate__c/InvoiceTemplate__c.object-meta.xml
<CustomObject>
    <label>Invoice Template</label>
    <nameField>
        <label>Invoice Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Project__c/Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>The current status of the project.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Prepare</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Construct</fullName>
            </value>
            <value>
                <fullName>Monitor</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TimeCard__c/TimeCard__c.object-meta.xml
<CustomObject>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC{0000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeCard__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TimeCard__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Time Cards</relationshipLabel>
    <relationshipName>Time_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeCard__c/fields/InvoiceTemplate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Template</label>
    <referenceTo>InvoiceTemplate__c</referenceTo>
    <relationshipLabel>Time Cards</relationshipLabel>
    <relationshipName>Time_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeCard__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Milestone1_Project__c</referenceTo>
    <relationshipLabel>Time Cards</relationshipLabel>
    <relationshipName>Time_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeCard__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Cards</relationshipLabel>
    <relationshipName>Time_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeCard__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to bill</fullName>
                <default>true</default>
                <label>Ready to bill</label>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PM_generateInvoicePDF_VF_CTRL.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-18-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class PM_generateInvoicePDF_VF_CTRL {

    static final String TIME_STATUS='Ready to bill';
    public Invoice__c invoice {get;set;} 
    public List <TimeCard__c> times {get;set;}
    public Map <Integer,InvoicePosition> positionsMap {get;set;}
    public Decimal total_amount_all_resources {get;set;}
  
    public PM_generateInvoicePDF_VF_CTRL(ApexPages.StandardController controller) {
        invoice = (Invoice__c)controller.getRecord();
        System.debug('Salesforce id in ' + invoice);
        Id templateId = getTemplateId(invoice);
        times=getTimes(templateId);
        positionsMap= getInvoicePositions(times, templateId);
        // temp
    }

    public PageReference updateInvoice(){
        PM_InvoiceUtils invoiceUtils = new PM_InvoiceUtils();
        invoiceUtils.setInvoiceAmount(invoice, total_amount_all_resources);
        return null;
    }


    public List <TimeCard__c> getTimes(Id templateId) {
        return [SELECT Date__c, Invoicetemplate__c, Description__c, Project__r.Name, Hours__c, Resource__c
        FROM TimeCard__c
        WHERE Invoicetemplate__c=:templateId
        AND Status__c=:TIME_STATUS
        order by Date__c asc];
    }

    public Id getTemplateId(Invoice__c invoice) {
        return [select id, InvoiceTemplate__c from Invoice__c where id=:invoice.id].InvoiceTemplate__c;
    }

    public Map <Integer,InvoicePosition> getInvoicePositions(List <TimeCard__c> times, Id templateId) {
        total_amount_all_resources=0;
        Map <Integer,InvoicePosition> positionsMap = new Map <Integer,InvoicePosition>();
        List <AssignResourse__c> resources=[select Contact__c, DailyRate__c, ProjectRole__c from AssignResourse__c where InvoiceTemplate__c=:templateId];
        
        for(Integer i=0; i<resources.size(); i++){
            Decimal hours = 0;
            Decimal amount;
            for (TimeCard__c t: times){
                if (t.Resource__c==resources[i].Contact__c){
                    hours = hours + t.Hours__c;
                    amount=hours*resources[i].DailyRate__c;
                    InvoicePosition invoicePosition = new InvoicePosition(resources[i].ProjectRole__c,resources[i].DailyRate__c, hours, amount );
                    positionsMap.put(i+1, invoicePosition);
                }
            }
            if (!positionsMap.KeySet().IsEmpty()){
                total_amount_all_resources=total_amount_all_resources + positionsMap.get(i+1).amount;
            }
        }
        return positionsMap;
    }

    public class InvoicePosition{
        public String provided_service {get;set;}
        public Decimal daily_rate {get;set;}
        public Decimal worked_hours {get;set;}
        public Decimal amount {get;set;}

        public InvoicePosition(String provided_service, Decimal daily_rate, Decimal worked_hours, Decimal amount) {
            this.provided_service = provided_service;
            this.daily_rate = daily_rate;
            this.worked_hours= worked_hours;
            this.amount=amount;
        }
    }
}