force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AmountNetto__c.field-meta.xml
<CustomField>
    <fullName>AmountNetto__c</fullName>
    <label>Amount Netto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/AmountTotal__c.field-meta.xml
<CustomField>
    <fullName>AmountTotal__c</fullName>
    <label>Amount Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceSentDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceSentDate__c</fullName>
    <label>Invoice Sent Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PM_InvoiceUtils.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 10-31-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   10-23-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class PM_InvoiceUtils {

    public static void updateInvoiceStatus (Invoice__c invoice){
       try{     
            invoice.Status__c='sent';
            invoice.InvoiceSentDate__c=Date.today();

            update invoice;
        }catch(Exception e){
            System.debug(Constants.ERROR_MESSAGE+e.getMessage());
        }
    }

    // To Do currently is set by the VF page controller PM_generateInvoicePDF_VF_CTRL
    public void setInvoiceAmount (Invoice__c invoice, Decimal totalamount){
        try{     
            invoice.AmountNetto__c=totalamount;
            invoice.VAT__c=0.19*totalamount;
            invoice.AmountTotal__c=invoice.AmountNetto__c+invoice.VAT__c;
            update invoice;
         }catch(Exception e){
             System.debug(Constants.ERROR_MESSAGE+e.getMessage());
         }
     }

}