force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PM_generateInvoicePDF_CTRLTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 10-27-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   10-27-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@isTest
public class PM_generateInvoicePDF_CTRLTest {
/*
    @testSetup 
    static void setup() {
        // Create common test Contact
        Contact contactObject = TestDataFactory.createContact();
        Invoice__c germanInvoiceObj = TestDataFactory.createInvoice('German', contactObject.Id );
        Invoice__c englishInvoiceObj = TestDataFactory.createInvoice('English', contactObject.Id );
    }

    @isTest static void processGermanInvoice() {

        List <Invoice__c> currentInvoiceList = [select Id, BillingContact__c, Status__c, Name, Language__c FROM Invoice__c where Language__c='German'];
        
        Test.startTest();
        PM_generateInvoicePDF_CTRL.executeActivitiesOnInvoice(currentInvoiceList.get(0).Id, 'German');
        Test.stopTest();

    }
*/
    /*@isTest static void processEnglishInvoice() {

        List <Invoice__c> currentInvoiceList = [select Id, BillingContact__c, Status__c, Name, Language__c FROM Invoice__c where Language__c='English'];

        Test.startTest();
        PM_generateInvoicePDF_CTRL.executeActivitiesOnInvoice(currentInvoiceList.get(0).Id, 'English');
        Test.stopTest();

    }*/

}