force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/InvoiceTemplate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Template</label>
    <referenceTo>InvoiceTemplate__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PerformanceMonth__c.field-meta.xml
<CustomField>
    <fullName>PerformanceMonth__c</fullName>
    <formula>TEXT(Month__c) + &apos;, &apos;+ TEXT(YEAR(DATEVALUE(CreatedDate)))
/*TEXT(Month__c) + &apos;, &apos;+TEXT(YEAR(TODAY()))
TEXT(Month__c) + &apos;, &apos;+&apos;2022&apos;*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Performance Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceTemplate__c/InvoiceTemplate__c.object-meta.xml
<CustomObject>
    <label>Invoice Template</label>
    <nameField>
        <label>Invoice Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceTemplate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Templates</relationshipLabel>
    <relationshipName>Invoice_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NotificationService.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-22-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   10-21-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class NotificationService {

    public static Boolean sendResult=true;
    public static String sendErrorMessage;

    // send Email message with preddefined Template
    public static void sendEmail( EmailTemplate emailTemplate, Invoice__c currentInvoice, List <Id> filesList ){

        String billingEmail=currentInvoice.InvoiceTemplate__r.Account__r.BillingEmail__c;
        String emailSubject= 'Rechnung '+ currentInvoice.Name + ' Lesitungszeitraum '+ currentInvoice.PerformanceMonth__c + ' - Salesforce Technical Architect';
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        try{
            message.setSenderDisplayName('Lanespot Solutions'); 
            message.setUseSignature(false);
            message.setBccSender(false); 
            message.setSaveAsActivity(false);
            message.setSubject(emailSubject);
            message.setEntityAttachments(filesList);
            message.setHtmlBody(emailTemplate.htmlvalue);
            message.toAddresses = new String[] { billingEmail};
            String[] bccAddresses = new String[] {Constants.BccEmailAddresses};
            // Add the BCC addresses
            message.setBccAddresses(bccAddresses);
            Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage> {message};
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            System.debug('The email was sent successfully. '+results[0].success);

        }catch(Exception e){
            sendResult=false;
            sendErrorMessage=Constants.ERROR_MESSAGE+e.getMessage();
            System.debug(Constants.ERROR_MESSAGE+e.getMessage());
        }
     }
}