force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/InvoiceTemplate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Template</label>
    <referenceTo>InvoiceTemplate__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PerformanceMonth__c.field-meta.xml
<CustomField>
    <fullName>PerformanceMonth__c</fullName>
    <formula>TEXT(Month__c) + &apos;, &apos;+ TEXT(YEAR(DATEVALUE(CreatedDate)))
/*TEXT(Month__c) + &apos;, &apos;+TEXT(YEAR(TODAY()))
TEXT(Month__c) + &apos;, &apos;+&apos;2022&apos;*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Performance Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceTemplate__c/InvoiceTemplate__c.object-meta.xml
<CustomObject>
    <label>Invoice Template</label>
    <nameField>
        <label>Invoice Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceTemplate__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Templates</relationshipLabel>
    <relationshipName>Invoice_Templates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeCard__c/TimeCard__c.object-meta.xml
<CustomObject>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC{0000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeCard__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Time Cards</relationshipLabel>
    <relationshipName>Time_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeCard__c/fields/InvoiceTemplate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Template</label>
    <referenceTo>InvoiceTemplate__c</referenceTo>
    <relationshipLabel>Time Cards</relationshipLabel>
    <relationshipName>Time_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeCard__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to bill</fullName>
                <default>true</default>
                <label>Ready to bill</label>
            </value>
            <value>
                <fullName>Billed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PM_generateInvoicePDF_CTRL.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-28-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   10-20-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class PM_generateInvoicePDF_CTRL {

    public static String messageResponse ='success';
    static final String TIME_STATUS='Ready to bill';
    public static Invoice__c currentInvoice;
    public static EmailTemplate emailTemplate;

    @AuraEnabled
    public static String executeActivitiesOnInvoice (Id invoiceId, String language){

        pageReference pdfInvoiceTemplate = language == 'German' ? Page.PM_generateInvoicePDF_DE: Page.PM_generateInvoicePDF_EN;

        if (language == 'German'){
            emailTemplate=[SELECT Id,name,Body,htmlvalue, Subject FROM EmailTemplate where DeveloperName=:Constants.EmailTemplate_SendInvoice_DE_ID];
        } else if (language == 'English'){
            emailTemplate=[SELECT Id,name,Body,htmlvalue, Subject FROM EmailTemplate where DeveloperName=:Constants.EmailTemplate_SendInvoice_EN_ID];
        } else {
            system.debug('no templaze has beed selected');
        }

        List <Invoice__c> currentInvoiceList= [select Id, InvoiceTemplate__r.Name, PerformanceMonth__c, InvoiceTemplate__r.Account__r.BillingEmail__c, InvoiceTemplate__c, Status__c, Name FROM Invoice__c where id=:invoiceId WITH SECURITY_ENFORCED];
        Id currentInvoiceId=currentInvoiceList.get(0).Id;
        if (!currentInvoiceList.IsEmpty()){
            currentInvoice = currentInvoiceList.get(0);
        }
        
        pdfInvoiceTemplate.getParameters().put('id',currentInvoiceId);
        //Blob body = pdfInvoiceTemplate.getContentAsPDF();
        Blob body;
        if(Test.isRunningTest()){
            body = blob.valueOf('test');
        }else {
            body = pdfInvoiceTemplate.getContentAsPDF();
        }

            //create a pdf file from the VF page
            Id documentId = FileService.createFile(body, currentInvoice);
            // add or created relation of invoice file to email template and invoice record
            List<Id> listOfRecs = new List<Id>();
            ListOfRecs.add(currentInvoiceId);
            FileService.AttachOrReplaceFilesToRecords(documentId, listOfRecs);
            
            // send email to the customer with the attached invoice as pdf file
            List <Id> filesList = new List <Id>();
            filesList.add(documentId);


            NotificationService.sendEmail(emailTemplate, currentInvoice,filesList);
            if (NotificationService.sendResult){
                PM_InvoiceUtils.updateInvoiceStatus(currentInvoice);
                PM_InvoiceUtils.upsertRevenues();
                PM_TimeCard_Service.updateTimeCardStatus(currentInvoice);

            }
            else {
                messageResponse = NotificationService.sendErrorMessage;
            }
        
        return messageResponse;
    }

    private static Boolean validateTimeStatus (Id invoiceTemplateId){
        Boolean allTimesBilled;
        Map<ID, TimeCard__c> m = new Map<ID, TimeCard__c>([SELECT Status__c FROM TimeCard__c where InvoiceTemplate__c=:invoiceTemplateId]);
        for (ID idKey : m.keyset()) {
            // if only one record is ready to bill, set the parameter to true
            if (String.valueOf(m.get(idKey))==TIME_STATUS){
                allTimesBilled= true;
            } else{
                allTimesBilled= false;
            }
        }
        return allTimesBilled;
    }
}