force-app/main/default/objects/EURConfig__mdt/EURConfig__mdt.object-meta.xml
<CustomObject>
    <label>EUR Config</label>
    <pluralLabel>EUR Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/EURConfig__mdt/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Steuer Jahr</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2022</fullName>
                <default>true</default>
                <label>2022</label>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/AmountNetto__c.field-meta.xml
<CustomField>
    <fullName>AmountNetto__c</fullName>
    <formula>IF(ISPICKVAL(SubCategory__c, &quot;Bewirtungsaufwendungen&quot;),0.7*(AmountNetto19__c+AmountNetto7__c), AmountNetto19__c+AmountNetto7__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Netto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/DateIncurred__c.field-meta.xml
<CustomField>
    <fullName>DateIncurred__c</fullName>
    <label>Date Incurred</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/SubCategory__c.field-meta.xml
<CustomField>
    <fullName>SubCategory__c</fullName>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waren, Rohstoffe und Hilfsstoffe einschließlich der Nebenkosten</fullName>
            </value>
            <value>
                <fullName>Bezogene Fremdleistungen</fullName>
            </value>
            <value>
                <fullName>Ausgaben für eigenes Personal</fullName>
            </value>
            <value>
                <fullName>Aufwendungen für Telekommunikation</fullName>
            </value>
            <value>
                <fullName>Übernachtungs- und Reisenebenkosten bei Geschäftsreisen des Steuerpflichtigen</fullName>
            </value>
            <value>
                <fullName>Fortbildungskosten</fullName>
            </value>
            <value>
                <fullName>Kosten für Beratungsleistungen und Buchführung</fullName>
            </value>
            <value>
                <fullName>Miete / Leasing für bewegliche Wirtschaftsgüter (ohne Kraftfahrzeuge)</fullName>
            </value>
            <value>
                <fullName>Beiträge, Gebühren, Abgaben und Versicherungen</fullName>
            </value>
            <value>
                <fullName>Werbekosten</fullName>
            </value>
            <value>
                <fullName>Schuldzinsen</fullName>
            </value>
            <value>
                <fullName>Gezahlte Vorsteuerbeträge</fullName>
            </value>
            <value>
                <fullName>An das Finanzamt gezahlte und ggf. verrechnete Umsatzsteuer</fullName>
            </value>
            <value>
                <fullName>Bildung von Rücklagen</fullName>
            </value>
            <value>
                <fullName>Übrige unbeschränkt abziehbare Betriebsausgaben</fullName>
            </value>
            <value>
                <fullName>Bewirtungsaufwendungen</fullName>
            </value>
            <value>
                <fullName>Geschenke</fullName>
            </value>
            <value>
                <fullName>Leasingkosten, Steuern, Versicherungen und Maut</fullName>
            </value>
            <value>
                <fullName>Sonstige tatsächliche Fahrkosten</fullName>
            </value>
            <value>
                <fullName>Fahrtkoste für gewerblich genutzte Privatfahrzeuge</fullName>
            </value>
            <value>
                <fullName>Wege zwischen Wohnung und erster Betriebsstätte und Familienheimfahrten</fullName>
            </value>
            <value>
                <fullName>GWG</fullName>
            </value>
            <value>
                <fullName>Verpflegungsmehraufwendungen</fullName>
            </value>
            <value>
                <fullName>Bürobedarf</fullName>
            </value>
            <value>
                <fullName>Spenden</fullName>
            </value>
            <value>
                <fullName>Kinderbetreuung</fullName>
            </value>
            <value>
                <fullName>Krankenkasse</fullName>
            </value>
            <value>
                <fullName>Rente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Betriebsausgaben</fullName>
            </value>
            <value>
                <fullName>Raumkosten und sonstige Grundstücksaufwendungen</fullName>
            </value>
            <value>
                <fullName>Sonstige unbeschränkt abziehbare Betriebsausgaben</fullName>
            </value>
            <value>
                <fullName>Beschränkt abziehbare Betriebsausgaben und Gewerbesteuer</fullName>
            </value>
            <value>
                <fullName>Kraftfahrzeugkosten und andere Fahrtkosten</fullName>
            </value>
            <value>
                <fullName>Absetzung für Abnutzung (AfA)</fullName>
            </value>
            <value>
                <fullName>Privatentnahme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <formula>IF(Not(NoVat__c), 0.19*AmountNetto19__c+0.07*AmountNetto7__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AmountNetto__c.field-meta.xml
<CustomField>
    <fullName>AmountNetto__c</fullName>
    <label>Amount Netto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceSentDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceSentDate__c</fullName>
    <label>Invoice Sent Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PM_EUR_Ctrl.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-16-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class PM_EUR_Ctrl {

    public Income income {get;set;}
    public Expense expense {get;set;}
    public Integer currentYear{get;set;}
    public Decimal profit{get;set;}
    public Decimal paidTaxesFinal{get;set;}

    public PM_EUR_Ctrl() {
        //currentYear = System.Today().year();
        String year= EURConfig__mdt.getInstance('CurrentYear').Year__c;
        currentYear=integer.valueof(year);
        income=getIncomes(currentYear);
        expense=getExpenses(income.paid_taxes, currentYear);
        profit=getProfit(income.total_income, expense.total_expense);
    }

    private static Income getIncomes(Integer currentYear) {
        Income tmpIncome = new Income();
        Decimal tmp_taxed_income=0;
        Decimal tmp_paid_taxes=0;
 
        for (Invoice__c invoice: [SELECT AmountNetto__c, VAT__c FROM Invoice__c WHERE CALENDAR_YEAR(InvoiceSentDate__c) =:currentYear and status__c!='Draft']){
            tmp_taxed_income=tmp_taxed_income+invoice.AmountNetto__c;
            tmp_paid_taxes=tmp_paid_taxes+invoice.VAT__c;
            tmpIncome.taxed_income=tmp_taxed_income;
            tmpIncome.paid_taxes=tmp_paid_taxes;
            tmpIncome.total_income= tmpIncome.taxed_income+tmpIncome.paid_taxes;
        }

        return tmpIncome;
    }

    private static Expense getExpenses(Decimal liableTaxes, Integer currentYear) {
        Expense exp = new Expense();

        Decimal paid_input_taxes_temp=0;

        Decimal operating_outcomes_temp=0;
        Decimal property_outcomes_temp=0;
        Decimal afa_temp=0;
        Decimal fully_deductible_outcomes_temp=0;
        Decimal limited_deductible_outcomes_temp=0;
        Decimal vehicle_outcomes_temp=0;
        Decimal total_expense_temp=0;
        // variable privat Entnahmen
        Decimal private_outcomes_temp=0;

        for (Expense__c expense: [SELECT AmountNetto__c, VAT__c, Type__c, Subcategory__c FROM Expense__c WHERE CALENDAR_YEAR(DateIncurred__c)=:currentYear]){
            
            switch on expense.type__c {
                when 'Betriebsausgaben' {
                    operating_outcomes_temp=operating_outcomes_temp + expense.AmountNetto__c;
                    exp.operating_outcomes=operating_outcomes_temp;
                }
                when 'Afa' {
                    afa_temp=afa_temp+expense.AmountNetto__c;
                    exp.afa=afa_temp;
                }
                when 'Raumkosten und sonstige Grundstücksaufwendungen' {
                    property_outcomes_temp=property_outcomes_temp+expense.AmountNetto__c;
                    exp.property_outcomes=property_outcomes_temp;
                }
                when 'Sonstige unbeschränkt abziehbare Betriebsausgaben' {
                    fully_deductible_outcomes_temp=fully_deductible_outcomes_temp+expense.AmountNetto__c;
                    exp.fully_deductible_outcomes=fully_deductible_outcomes_temp;
                    
                }
                when 'Beschränkt abziehbare Betriebsausgaben und Gewerbesteuer' {
                    limited_deductible_outcomes_temp=limited_deductible_outcomes_temp+expense.AmountNetto__c;
                    exp.limited_deductible_outcomes=limited_deductible_outcomes_temp;
                }
                when 'Kraftfahrzeugkosten und andere Fahrtkosten' {
                    vehicle_outcomes_temp=vehicle_outcomes_temp+expense.AmountNetto__c;
                    exp.vehicle_outcomes=vehicle_outcomes_temp;
                }
            }
            paid_input_taxes_temp=paid_input_taxes_temp+expense.VAT__c;
            total_expense_temp=total_expense_temp+expense.AmountNetto__c;
            exp.paid_input_taxes=liableTaxes-paid_input_taxes_temp;
            exp.total_expense=total_expense_temp+exp.paid_input_taxes;

            // start of private outcomes
            /*switch on expense.subcategory__c {
                when 'Krankenkasse' {
                    private_outcomes_temp=private_outcomes_temp+expense.AmountNetto__c;
                    private_outcomes=private_outcomes_temp;
                }
                when 'Rente' {

                }
                when 'Spenden' {

                }
                when 'Kinderbetreuung' {
                    private_outcomes_temp=private_outcomes_temp+expense.AmountNetto__c;
                    private_outcomes=private_outcomes_temp;
                }
                when 'Andere Privatentnahmen' {

                }
            }*/


        }

        return exp;
    }

    private static Decimal getProfit(Decimal total_income, Decimal total_expense) {
        return total_income-total_expense;
    }

    
    public class Income{
        public Decimal taxed_income {get;set;}
        public Decimal taxedfree_income {get;set;}
        public Decimal paid_taxes {get;set;}
        public Decimal refunded_taxes {get;set;}
        public Decimal private_car_use {get;set;}
        public Decimal total_income {get;set;}
    }

    public class Expense{
        public Decimal paid_input_taxes{get;set;}
        public Decimal total_expense{get;set;}
        public Decimal operating_outcomes {get;set;}
        public Decimal property_outcomes {get;set;}
        public Decimal afa {get;set;}
        public Decimal fully_deductible_outcomes {get;set;}
        public Decimal limited_deductible_outcomes {get;set;}
        public Decimal vehicle_outcomes {get;set;}
        // private Entnahmen
        public Decimal private_outcomes {get;set;}

    }
}